import { Router } from 'express';
import { authenticate } from '../../middleware/auth';
import { requireFeature } from '../../middleware/planLimits';
import { validate } from '../../middleware/validate';
import { voiceParseSchema, suggestSchema, commandSchema } from './ai.validation';
import { parseVoice, suggestSolution, parseCommand, autoCreateTicket } from './ai.controller';
import { requireWorkspace, withWorkspaceMembership } from '../../middleware/workspace';
const router = Router();
router.post('/voice-parse', authenticate, requireWorkspace, requireFeature('ai'), validate(voiceParseSchema), parseVoice);
router.post('/suggest', authenticate, requireWorkspace, requireFeature('ai'), validate(suggestSchema), suggestSolution);
router.post('/command', authenticate, requireWorkspace, requireFeature('ai'), validate(commandSchema), parseCommand);
router.post('/auto-ticket', authenticate, requireWorkspace, withWorkspaceMembership, autoCreateTicket);
export default router;
